<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ramsunkara" ignored="0" name="Default test" tests="3" failures="1" timestamp="22 Jun 2019 19:03:57 GMT" time="6.204" errors="0">
  <testcase name="testcase1" time="0.01" classname="ReportsRS.ExtentReportDemo"/>
  <testcase name="testcase2" time="5.104" classname="ReportsRS.ExtentReportDemo">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method ReportsRS.ExtentReportDemo.testcase2() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method ReportsRS.ExtentReportDemo.testcase2() didn't finish within the time-out 5000
]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase3" time="0.006" classname="ReportsRS.ExtentReportDemo">
    <skipped/>
  </testcase> <!-- testcase3 -->
</testsuite> <!-- Default test -->
