<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6204" started-at="2019-06-22T19:03:51Z" finished-at="2019-06-22T19:03:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6204" started-at="2019-06-22T19:03:51Z" finished-at="2019-06-22T19:03:57Z">
      <class name="ReportsRS.ExtentReportDemo">
        <test-method status="PASS" signature="generatereport()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="generatereport" is-config="true" duration-ms="317" started-at="2019-06-22T19:03:51Z" finished-at="2019-06-22T19:03:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generatereport -->
        <test-method status="PASS" signature="testcase1()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="testcase1" duration-ms="10" started-at="2019-06-22T19:03:52Z" finished-at="2019-06-22T19:03:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method status="PASS" signature="endreport()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="endreport" is-config="true" duration-ms="520" started-at="2019-06-22T19:03:52Z" finished-at="2019-06-22T19:03:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endreport -->
        <test-method status="FAIL" signature="testcase2()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="testcase2" duration-ms="5104" started-at="2019-06-22T19:03:52Z" finished-at="2019-06-22T19:03:57Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method ReportsRS.ExtentReportDemo.testcase2() didn't finish within the time-out 5000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method ReportsRS.ExtentReportDemo.testcase2() didn't finish within the time-out 5000
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method status="PASS" signature="endreport()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="endreport" is-config="true" duration-ms="90" started-at="2019-06-22T19:03:57Z" finished-at="2019-06-22T19:03:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endreport -->
        <test-method status="SKIP" signature="testcase3()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="testcase3" duration-ms="6" started-at="2019-06-22T19:03:57Z" finished-at="2019-06-22T19:03:57Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skiping testcase]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skiping testcase
at ReportsRS.ExtentReportDemo.testcase3(ExtentReportDemo.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
        <test-method status="PASS" signature="endreport()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="endreport" is-config="true" duration-ms="73" started-at="2019-06-22T19:03:57Z" finished-at="2019-06-22T19:03:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endreport -->
        <test-method status="PASS" signature="close()[pri:0, instance:ReportsRS.ExtentReportDemo@6767c1fc]" name="close" is-config="true" duration-ms="42" started-at="2019-06-22T19:03:57Z" finished-at="2019-06-22T19:03:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- ReportsRS.ExtentReportDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
